### ISSUE TITLE
EditorConfig for VS Code compatibility with FileSystemProvider

### ISSUE THREAD

**Issue by CasaDeRobison** [editorconfig/editorconfig-vscode#203]
Please fill-in this template.

- [X] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.28.2`            | `0.12.5`             |

### Additional comments or steps to reproduce

There may be nothing that can be done, and I'm making an assumption here, but wanted to raise the "issue" just in case it hasn't been observed previously.

Installed the EditorConfig extension. If used on a local file system all works as one would expect. If used in conjuction with the SSH FS extension (version 1.11.1), no attempt is made to find an .editorconfig file, either in the same remote directory as the file being edited or in the remote parent directory of the file being edited.

I suspect the issue is due to the way the SSH FS extension is implemented using the FileSystemProvider interface exposed in more recent versions of VS Code. It may or may not be possible to support such extensions. I do not know. If it is possible that would be great. If it is not possible ... then so be it.

Thanks for reading my report. If you need further information I'll be glad to provide it, but given that the extension works for normal usage, I think a lot of the details from the template are irrelevent so I just cut them out. My apologies if that assumption is incorrect.

**Comment by osechet** [comment]
I don't think the issue is specific to SSH FS. It's probably related to the FileSystemProvider API introduced by vscode 1.23.0. It would be a good thing if editorconfig extension could support that API.

**Comment by jedmao** [comment]
@osechet I'm not sure it makes sense for this extension to leverage the [FileSystemProvider API](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), because of the way EditorConfig works, in that it traverses up the folder structure, merging any/all `.editorconfig` files found until it finds one with `root=true` in it. That would be a bit thrashing on a remote system and I'm not even sure that would be possible using the [FileSystemProvider API](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider).

That said, if you can figure it out, feel free to submit a PR!

**Comment by jedmao** [comment]
Closing, as this issue has become stale w/o providing any additional context.
