### ISSUE TITLE
Will spaces automatically converted?

### ISSUE THREAD

**Issue by axelf** [editorconfig/editorconfig-vscode#227]
Please fill-in this template.

- [X ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.31.1`            | `0.13.0`             |

### Root `.editorconfig` File

```ini
root = true

[*]
indent_style = tab
indent_size = 4
```

I don't know if i understand the extension the right way. Imagine i have an old file with spaces and load it into VS Code. Does it automatically convert the spaces to tabs by placing the .editorconfig in root folder?

**Comment by jedmao** [comment]
I believe vscode used to behave differently back in the day and it would basically enforce one indentation type. That doesn't seem to be the case right now, so it begs the question of whether this extension should be doing this. If so, I think the proper strategy would be different depending on your EditorConfig settings.

## indent_style = space
- Detect indentation from content.
- Convert indentation to tabs.
- Set tab size to `indent_size` setting.
- Convert indentation to spaces.

## indent_style = tab
- Detect indentation from content.
- Convert indentation to tabs.
- Set tab width.

Even doing the above has the potential to introduce some weird behavior. In fact, I've worked on projects where they demand we don't change the existing indentation, even if it's broken, because they don't want to see those types of changes in every single PR.

I can see the argument on both sides, but I think this is a gray topic.

Suffice it to say, no. This extension doesn't currently do any conversions. It just enforces future input.

**Comment by jedmao** [comment]
Honestly, I don't think we should be doing anything fancy. Just let the editor do its job. EditorConfig is more about setting the editor's settings to the appropriate settings, which this extension does quite well.

**Comment by axelf** [comment]
Hi, thank you for all the infos. Now i know how it works and i also think the extension should do one thing. For the other things i use vs code itself.

**Comment by felixpenrose** [comment]
I see that this topic has been discussed a few times so I apologies, but I just wanted to add my opinion as I've just recently switched from sublime to VSC and the sublime version of editorconfig _does_ seem to perform this conversion from (in my case) tabs to spaces. I don't believe I have another extension that performs this action, though I may be wrong, I've a fair few of them!

Our team some time ago decided to switch from tabs to spaces, and I can certainly understand the negative aspect of making this a default feature, as for a long time our PR's were very messy, though ignoring white space in them for us made this a non issue. I can see this not being an option for many teams though.

I would agree this should not be default behaviour, but is it something that could be made _optional_ behaviour?

For our team, it would have been a **lot** harder to change from tabs to spaces were it not for the auto conversion upon saving a file, and I'm really going to miss this feature when working on some older files. The automation saved so much time.

**Comment by jedmao** [comment]
How would one opt into this optional behavior? There are tools like Prettier that support EditorConfig as well as multiple file formats. I would recommend using Prettier on file save. That's what I've been doing on my projects. Just commit a .vscode folder into your repo with the format on save option. If that doesn't fly, use husky and lint-staged to do it on each commit. I do both.

**Comment by ffes** [comment]
Know that there is a builtin function in vscode to covert indentions to space or tabs manually. Search for `convert` in the command pallette.

**Comment by jedmao** [comment]
Which, to be clear, cannot be done reliably without AST-aware transformations, which is how Prettier works.

**Comment by Novocaine88** [comment]
I'm aware of the manual method, however this is not a solution. The whole point of editorconfig is to provide consistency automatically. Manual fixes are irrelevant in this regard.

Working in a team, you cannot guarantee everyone will follow suit, that's why automation like this necessary.

I'm looking into Prettier now, though working with PHP, there's only an alpha package currently available.

To make this optional could it not be an additional configuration setting?

**Comment by jedmao** [comment]
It is not within the design goals of EditorConfig to fix projects that already have inconsistencies, but rather to configure one's editor so as not to introduce more inconsistencies going forward; hence, the name, EditorConfig.

**Comment by felixpenrose** [comment]
Surely though the settings `trim_trailing_whitespace` and `insert_final_newline` are retroactively fixing past inconsistencies? Granted converting a whole document from one indentation standard to another _is_ a much more disruptive task, but is it along the same lines as these two existing rules.

Additionally, I've just tested on a fresh install of sublime text and this automatic conversion from tabs to spaces does happen (and back again if I change the config form spaces -> tabs). Should this behaviour not be consistent between editors?

**Comment by ffes** [comment]
It is very hard to make behavior really consistent between editors. There are so many of them.

Apparently Sublime does this, but I was not aware of any EditorConfig plugin that behaves like that before you mentioned it here.

Some (maybe even most) of them can do a basic conversion, but no editor has enough knowledge about all the programming languages out there to perform such a fix really reliable. So I don't see fixing these kind of things ever going to implement consistent between editors by a generic EditorConfig plugin.

**Comment by felixpenrose** [comment]
I see, all valid points.

It's a shame this won't be added it really is the _only_ thing I'll miss from sublime, not a big issue, just was a nice time saver and helped consistency.

**Comment by jedmao** [comment]
I'm also a fan of consistency, which is why I wrote this document for plugin/extension developers: https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines#indent_style

You can always write a separate plugin that does what you want or look for an existing one. The EditorConfig API is still available to you. I even modified this extension to be compostable. Knock yourself out!

**Comment by skela** [comment]
@jedmao how about a new property called `convert_to_indent_style` that would convert the indentation style to the desired indent style on save. If you made this property default to false, it ought to be a safe thing to add.

i still havent found an easy way to convert spaces into tabs on save, i hate that the whole world seems to think spaces are better :'(

**Comment by jedmao** [comment]
> @jedmao how about a new property called `convert_to_indent_style` that would convert the indentation style to the desired indent style on save. If you made this property default to false, it ought to be a safe thing to add.
> 
> i still havent found an easy way to convert spaces into tabs on save, i hate that the whole world seems to think spaces are better :'(

I share your sentiment, but this isn’t the place for general EditorConfig feature requests.
