### ISSUE TITLE
EditorConfig modifies selection incorrectly when the extension host is busy

### ISSUE THREAD

**Issue by rebornix** [editorconfig/editorconfig-vscode#236]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.36`            | `0.13.0`             |

### Additional comments or steps to reproduce

Originally posted in https://github.com/microsoft/vscode/issues/71238 but turns out to be an EditorConfig extension issue. EditorConfig seems to listen to document content change event and attempts to update the cursor position. When users install both EditorConfig and Vim extension, and use Vim keybindings to edit the document, there are chances that EditorConfig messes up with the selection, especially when there is a long running task in the extension host. More details are listed in https://github.com/microsoft/vscode/issues/71238#issuecomment-516624237

**Comment by jedmao** [comment]
Thanks for the report. I'll be looking into this.

**Comment by alexdima** [comment]
@jedmao I think the selection is being set here -- https://github.com/editorconfig/editorconfig-vscode/blob/7783f2334c267cfec376c236bdf9bbf7a4a7778d/src/DocumentWatcher.ts#L98

Is that still necessary? That code was added back in 2017 and we've had quite a handful of fixes in VS Code for better preserving the selection when doing edits since then.

If setting the selection is still necessary, could it please be rewritten to set the selection only if there are actual transformations applied? As it stands, I believe that code always executes, i.e. the selection is always set, even if there are no transformations done to the file.

**Comment by alexdima** [comment]
I've created a PR to set the editor selection only when edits are applied -- https://github.com/editorconfig/editorconfig-vscode/pull/262
