### ISSUE TITLE
Saving files affects the file history

### ISSUE THREAD

**Issue by venomtm** [editorconfig/editorconfig-vscode#288]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.50.1-1`            | `v0.15.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.yml]
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? Yes / No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `2`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

All files

### Expected behavior

Only affect file history (undo/redo) when the file is actually changed.

### Actual behavior

Each save, even if nothing is changed, adds an entry to the file history. So if i make a change, press CTRL+S then make another change, I have to press CTRL+Z 3 times to undo both changes. If I press CTRL+S 10 times I have to press CTRL+Z 12 times to undo both changes.

**Comment by mathiasvr** [comment]
It seems this is only a problem when specifying `end_of_line`.

**Comment by venomtm** [comment]
Hi!

I can confirm that this is the case for me as well :).

Although, that parameter has been in my .editorconfig-file for quite some time now without those problems before.

Regards, Mikael

**Comment by mister-glass** [comment]
> Hi!
> 
> I can confirm that this is the case for me as well :).
> 
> Although, that parameter has been in my .editorconfig-file for quite some time now without those problems before.
> 
> Regards, Mikael

Yes, I have the same issue and it started happening when VS Code updated to 1.50. The problem still persists in VS Code 1.51.

**Comment by zoltan-patchworks** [comment]
Same here.

**Comment by zoltan-patchworks** [comment]
Is it possible to install an older version of the plugin if that's not affected?

**Comment by cruzdanilo** [comment]
this bug destroys `redo` history on save, which is a big problem.

**Comment by zoltan-patchworks** [comment]
Do you have any update on this?
@jedmao

**Comment by jedmao** [comment]
Fixed in #292, but keep in mind that you will still destroy redo history if there are inconsistent line endings in your file or if you have another rule like `insert_final_newline = true` and you save your file w/o a final newline. Any time EditorConfig has to step in to fix the file you will destroy redo history.

**Comment by zoltan-patchworks** [comment]
Thanks @jedmao .
At least we know that this is only happening when there are inconsistent line endings in the file.

So if we have `v0.16.1` of the plugin which is the current version on VS Marketplace, and the line endings are also consistent, it should not break the history, right?

Is it possible to config the plugin to leave line endings untouched and only apply line ending rules to new or changed lines?

**Comment by mathiasvr** [comment]
@jedmao Thanks works perfectly now.

**Comment by jedmao** [comment]
> So if we have `v0.16.1` of the plugin which is the current version on VS Marketplace, and the line endings are also consistent, it should not break the history, right?

To be clear, even if the line endings are consistent, but they don't match your `end_of_line` setting. Anything that would require EditorConfig to step in and enforce the rule is the issue here, but if you had an auto-save every one second, it would fix the line endings on the first auto-save so that subsequent auto-saves wouldn't require additional fixes to the line endings.
 
> Is it possible to config the plugin to leave line endings untouched and only apply line ending rules to new or changed lines?

This extension makes use of vscode's [`setEndOfLine`](https://code.visualstudio.com/api/references/vscode-api#TextEdit) method, which is functionally equivalent to changing the EOL sequence via the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) or in the status bar, followed by a save operation. VSCode does not support mixed line endings. They [normalize line endings on every file-save operation](https://github.com/microsoft/vscode/issues/53495#issuecomment-408144905), so it would be futile for this extension to do otherwise.
