### ISSUE TITLE
Questions regarding this extension

### ISSUE THREAD

**Issue by Joe23232** [editorconfig/editorconfig-vscode#304]
Hi, I find this extension to be very interesting and exciting but I do have some questions.

1. Am I able to format the [Rust](https://www.rust-lang.org/) programming langauge?
2. Are there any docs in regarding how to format Rust?
3. Am I able to format my Rust code where it adds extra spacing after the variable structure name and it aligns everything together while adding a `:` right before specifying the variable data type, for example:

```rust
struct Color
{
    red             : u32,
    blue            : u32,
    greenasds       : u32,
}
impl Color
{
    fn init() -> Self
    {
        Self
        {
            red             : 255,
            blue            : 255,
            greenasds       : 255,
        }
    }
}
```

Can I like literally format it specifically to my own likings? Does it have the ability to do low level formatting without relying on pre-built settings?
4. Is the code formatted instantaneously as I am typing my code?

**Comment by papb** [comment]
Hello! The short answer is No for all your 4 questions.

EditorConfig is generic to any text file. It only supports the following properties, which are very generic:

* `indent_style`
* `indent_size`
* `tab_width`
* `end_of_line`
* `charset`
* `trim_trailing_whitespace`
* `insert_final_newline`

These things can be applied to Rust source files, of course, as they can for any text file.

For question 4, the answer is No because EditorConfig applies itself whenever you *save* the file, not whenever you type a new character. However, I believe VSCode offers the possibility of aggressive auto-saving, in which it basically saves you type something, so the answer would become Yes in this case. I personally hate this feature of aggressive auto-saving though.

I do not have experience with the Rust language, but what you're looking for probably exists for Rust - it's just not this extension. You're looking for a language-specific code formatter. For example, for JavaScript, I use [Prettier](https://prettier.io/). Probably something similar exists for Rust.

**Comment by Joe23232** [comment]
Thanks very much :)
