### ISSUE TITLE
Installation GitHub Actions Failure

### ISSUE THREAD

**Issue by Peimaan** [editorconfig/editorconfig-vscode#316]
Please fill-in this template.

- [x ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

I tried to Install EditorConfig on MacBook Air M1, but it had a red Failure sign next to GitHub Actions, and I do not know what to do? would you-else help? 
<img width="1280" alt="Screen Shot 2021-07-05 at 5 30 53 PM" src="https://user-images.githubusercontent.com/86084821/124624042-87124600-de4a-11eb-9d2b-6361f80b3d7b.png">
This is a screenshot but it looks like it can. not be seen! At least I can not see here.

**Comment by nrayburn-tech** [comment]
Short answer, there is nothing for you to worry about regarding the Github Actions failing.  If you have any issues using the extension, I would need more information about what isn't working as you expect.


What you are seeing there is the readme for the repository.  The Github Actions is marked as failing because the last commit to the repository did not pass the Github Actions testing.  This is not the same as the currently published version that would be downloaded from the vscode marketplace.
