### ISSUE TITLE
Is it possible to trim all the trailing empty lines but the last one.

### ISSUE THREAD

**Issue by sarbbottam** [editorconfig/editorconfig-vscode#49]
If the file already has multiple empty lines at the end, it would be great to trim all but the last one. Would that be possible?

**Comment by jedmao** [comment]
This isn't a vscode extension issue, but an EditorConfig issue, which has been discussed before. The problem is that the `insert_final_newline` rule only "inserts" and does not "remove" lines, as the setting suggests. Now, if it were named `ensure_single_final_newline` or something to that effect, then it would make sense to work this way; however, this is not the case. As such, I'm afraid that nothing in the existing EditorConfig settings would support this feature.

**Comment by jmlntw** [comment]
I wrote a extension to do this.
https://marketplace.visualstudio.com/items?itemName=jmlntw.vscode-ensure-single-final-newline
