### ISSUE TITLE
tab_width isn't applied properly

### ISSUE THREAD

**Issue by cblp** [editorconfig/editorconfig-vscode#69]
My configuration is:
```ini
[*]
indent_size = 2
tab_width = 8
```
What I see in opened files is that **both** indentation size **and** tab width are set to 2.

I think, EditorConfig can't work properly because of https://github.com/Microsoft/vscode/issues/10339.

**Comment by jedmao** [comment]
@cblp, can you give me a short example of a file that would use both of these settings at the same time and why? I'm just having a hard time picturing a scenario in which this would be a good idea, but I'm all ears.

**Comment by cblp** [comment]
Are you asking for a file, using both indentation and tabs? Indentation is used in almost all programming languages, and tab character may be used in almost any text file. For example, I can indent my C code by 4 spaces and use tabulation in comments to align ASCII drawings.

Moreover, one can use tab even in indentation! Just look at any Makefile. Its syntax makes you indent bodies of recipes with tabulation. But using tabs to indent code inside recipes is too wastefully. So many people (at least, as I can see), use 2-4 spaces to indent inner blocks inside recipes.

Despite of all that, do you know, why somebody on Earth may want to change the tab size?

**Comment by cblp** [comment]
Here's an example of such Makefile.
```makefile
build:
	find -name '*.c' \
	| xargs
	    grep
	      --only-matching
	      pattern
```
Unfortunately, GIthub replaces tab character with 4 spaces, so we have to pretend there is a tab.

**Comment by jedmao** [comment]
Unfortunately, I don't know where the tab is supposed to be!

I think I get what you're saying now though... kinda. I'm personally a fan of tabs for indentation, spaces for alignment, so you would never see tabs follow indentation in one of my files. Here's why...

![tabs-vs-spaces](https://cloud.githubusercontent.com/assets/1058243/17745995/bab0ba4c-6473-11e6-871b-37927f913539.gif)

As such, I would never actually declare the `tab_width` setting in an `.editorconfig` file, because I believe the user should be in control of what they deem an appropriate tab size. As long as the rules are followed according to my animated GIF above, people can feel free to use whatever they want.

That said, are you still convinced of a need for a file with "tabs for alignment following indentation"? I believe this is what you're trying to achieve. I've always felt that was a big NO NO, but you have me 2nd guessing myself.

**Comment by olzaragoza** [comment]
```
[*]
indent_style = tab
tab_width = 4
```

![screen1](https://cloud.githubusercontent.com/assets/14199576/17745993/1a497c66-647c-11e6-9864-c771d59cbfdd.JPG)

this is what you want?

**Comment by jedmao** [comment]
Closing, as there has been no responses.
