### ISSUE TITLE
Tabs added in middle of line

### ISSUE THREAD

**Issue by samuelms1** [editorconfig/editorconfig-vscode#75]
Can we have an option to only tabify before a line starts (all tabs leading up to first char)?  Ideally spaces that occur inside a line would be left alone (treated like deliberate formatting).

**Comment by SamVerschueren** [comment]
Could you elaborate with an example? Don't understand the request.

**Comment by jedmao** [comment]
I understand exactly what you mean and I think it's totally out of the scope of this plugin, because the plugin is only intended to tell the editor what settings to use. I believe what you're proposing is that the editor setting dynamically change from tabs to spaces when you move from leading whitespace (indentation) into alignment or any text thereafter.

![image](https://cloud.githubusercontent.com/assets/1058243/18947435/ae6cd298-8665-11e6-8b76-a2d761867867.png)

If this is what you want, I suggest you write a different plugin. You can always leverage the EditorConfig settings in your own plugin. It doesn't have to be the official EditorConfig plugin though.

**Comment by SamVerschueren** [comment]
Oh ok, now I understand. I agree with @jedmao that it's out of scope.

**Comment by samuelms1** [comment]
Yes, that accurately describes what I was asking for.  As a team we've agreed to use tabs, but its painful anytime there is code alignment.  Might look fine in your editor but depending on the tab size it could look like garbage elsewhere (like in stash when reviewing pull requests or devs can have their own tab size that they prefer).

Thanks for reviewing the request.  So is the editorconfig plugin only used to set the configuration of editorconfig --- as in it doesn't also enforce the tabbing rules on the files?  I thought this plugin also had logic that did the actual tabbing, but maybe that's a separate process or library that does that.

**Comment by jedmao** [comment]
@samuelms1, the issue is that your team is using tab characters for both indentation AND alignment. As the animated GIF above illustrates, when tabs are used only for indentation and spaces for alignment that follows indentation, it doesn't matter what your tab width setting is, because it will always look perfect.

As for EditorConfig plugins in general, they are written by different authors, but from what I've seen, they are written to align with the philosophies of the specific editors in question. In this case, setting your tab settings in vscode not only sets the editor setting, but also enforces them to an extent, without any additional plugin code. This is a vscode philosophy and this plugin doesn't go against it. Quite frankly, it couldn't even if we wanted it to, based on the limitations of the editor itself as well as the API, which I think it's evidence that Microsoft is doing the right thing.

**Comment by samuelms1** [comment]
Thanks again.  I'll try using purely tabs for alignment.

**Comment by jedmao** [comment]
You mean purely tabs for indentation and purely spaces for alignment, yes?
