### ISSUE TITLE
Should this plugin support converting/fixing indentation?

### ISSUE THREAD

**Issue by TomasDuda** [editorconfig/editorconfig-vscode#85]
As requested in @jedmao's comment in my PR #84, let's discuss if this extension should support converting indentation.

I feel that a feature like this has its place in any EditorConfig extension. I'm specifying indent style in my .editorconfig, so I'd expect it to behave just like other properties (`end_of_line`, `insert_final_newline`, `trim_trailing_whitespace`).

All of the above mentioned properties change the file in some way (inconsistently in this extension, some are applied on load and some automatically on save, but that's for another issue).

I use .editorconfig as the single source of truth for line endings, indentation style etc. - so I expect EditorConfig to change my files accordingly to my config without remembering to format code manually all the time. Maybe I'm doing it wrong, who knows?

Thoughts?

**Comment by jedmao** [comment]
Based on various conversations with the EditorConfig team (and with myself), my argument against the inclusion of this feature is related to the presumption that the project goals of EditorConfig should be to – would you believe it – configure your editor? In essence, this means future proofing your code from introducing more inconsistencies, but it doesn't mean fixing pre-existing issues with the code (exceptions: `insert_final_newline` and `trim_trailing_whitespace`).

For example, imagine a project where all the files have mixed line endings. In non-vscode editors, the strategy of EditorConfig has NOT been to change those line endings on save. This is because [people very intentionally don't want to fix them](https://github.com/editorconfig/editorconfig-vscode/issues/57), because then, every time they push code, the diffs light up with so much red and green.

That said, the philosophies of EditorConfig don't always align with the philosophies of each respective editor and the EditorConfig approach there is to follow the editor-specific philosophy. In this case, [vscode has decided that newlines should never be mixed](https://github.com/editorconfig/editorconfig-vscode/pull/46#issuecomment-210569328) and we have adopted that philosophy "in this plugin" only, ready to adapt to any future philosophical changes that vscode might introduce.

Unfortunately, that means you might experience an inconsistent EditorConfig plugin experience as you use different editors. Fortunately, people tend to stick with their favorite editor most of the time and they do this for their own philosophical reasons. It seems even more important to me that the plugin follow the editor's philosophy rather than the other way around, assuming that the user has made an educated and informed decision to use their favorite editor because the editor's philosophies align mostly with their own.

In conclusion, until the vscode team decides, like they have with mixed newlines, that there should never be mixed indentation, this plugin shall not be trying to solve that problem either. It's not that we believe in a world of mixed indentation, because we all most definitely don't; rather, we believe it's not a problem to solve in this context or at this stage of a file's existence.

Personally, I believe that solving mixed indentation is an impossible problem to solve consistently and in all cases, unless you first parse the code into it's written language's AST and then reformat the code after the fact. This is, again, way outside the goals of the EditorConfig project, as it's a very language-agnostic tool and has no knowledge of parsing languages or AST.

How do you feel about these points?

**Comment by xuhdev** [comment]
I agree with @jedmao . However, for your purpose, you may consider a standalone fixer to be used, instead of being a feature of the editor extensions/plugins.

**Comment by SamVerschueren** [comment]
I agree with @jedmao as well. This doesn't feel like a use case for `EditorConfig` to solve. It's not that easy either, ESLint has a fixer to do that but even that one fails all the time. Especially when people start to work with smart tabs etc. So it's not just converting 2 or 4 spaces to a tab, there is more to it and ideally should be put inside a different extension.

**Comment by jedmao** [comment]
Or no extension at all. Vscode already has built-in features to:
  1. Detect Indentation from Content.
  1. Convert Indentation to Spaces.
  1. Convert Indentation to Tabs.

![image](https://cloud.githubusercontent.com/assets/1058243/19677570/874e0b24-9a5f-11e6-8bd9-0e96c196154c.png)

That said, I don't think there's any extension that will be able to do the job (accurately) w/o knowledge of the actual language in question and parsing into AST. It just can't be done. It's not a solvable problem w/o AST.

**Comment by TomasDuda** [comment]
I see. Thanks for your feedback!
