### ISSUE TITLE
Format code (Shift+Alt+F) does not apply .editorconfig rules

### ISSUE THREAD

**Issue by gghez** [editorconfig/editorconfig-vscode#86]

**Comment by SamVerschueren** [comment]
This is not the goal of EditorConfig imo.

**Comment by gghez** [comment]
It works in Webstorm with Format command  (Ctrl+Alt+L). One example, I add an .editorconfig to normalize .json files with spaces over tabs and indent size defined to 2. I do certainly not want to replace manually tabs by 2 spaces whereas code formater may do that.

**Comment by ffes** [comment]
It is a language specific feature (provided by extensions) and not in control of this plugin or core vscode.

For me it only works for C++ files. And with those files it makes a big mess of tabs and spaces. I have to manually adjust the setting for that formatter. You are right that you would expect the formatter respects the tab settings of a document (that EditorConfig controls).

But this feature is implemented in (in my case) the C++ extension, so it is "their fault". I opened a bug report for C++ at https://github.com/Microsoft/vscode-cpptools/issues/341

You have to get in contact with the author of the JSON formatter you use.

**Comment by gghez** [comment]
it should at least have some settings allowing to apply .editorconfig rules on save or format to let user decide.

**Comment by jedmao** [comment]
@gghez, there are only 2 EditorConfig rules that are **verbs**; thus, support changes on file save across editors:
  1. `trim_trailing_whitespace`
  1. `insert_final_newline`

These rules, as you requested, are already applied on save, so there's nothing new here.

All other rules are **nouns**; thus, should ideally be implemented on file open, by simply changing the editor's settings. In the case of vscode, this is possible, because the `end_of_line` setting works fine this way, but for other editors, they might actually have to do some kind of `end_of_line` changes on file save, which is a bit controversial. I think the vscode team made a great choice in ensuring no files can be saved with inconsistent line endings, which means we don't have to do anything hacky to support this rule.

Formatting code, however, has no place in EditorConfig, because it's a language-specific concern and EditorConfig is language-agnostic. The idea is that EditorConfig will configure the editor properly so that when you save a file, it's saved properly. This is exactly true for vscode, so there's really nothing more to do.

What everyone's saying above is accurate. You need to contact the plugin author for your JSON formatter and request they read the EditorConfig settings for that file before formatting a certain way. This is very doable, because there is an EditorConfig core library for Node.js, which is the same one that this plugin uses.

**Comment by gghez** [comment]
I now understand, thank you @SamVerschueren and @jedmao
